# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

variables:
  - group: 'frontend-production'

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: 20.x

  - script: npm install --global yarn
    displayName: 'Install Yarn'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn build
    displayName: 'Build the app'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web App'
    inputs:
      app_location: 'dist'
      skip_app_build: true
      azure_static_web_apps_api_token: $(deployment_token)
